### ISSUE TITLE
[iOS] Installation Issue: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by YangLeoZhao** [negativetwelve/react-native-heap-analytics#6]
This is the first time i am interacting with cocoapods. Thanks for any guidance.
I took the following steps in setting up react-native-heap-analytics.
1. npm install --save react-native-heap-analytics
2. sudo gem install cocoapods
3. pod setup --verbose
4. This is my Podfile 
> platform :ios, '9.0'
> target 'displayer' do
>   use_frameworks!
>   pod "react-native-heap-analytics", path: "../node_modules/react-native-heap-analytics"
> end
5. pod install
> At this point i saw two warnings:
> [!] The `displayer [Debug]` target overrides the HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-displayer/Pods-displayer.debug.xcconfig'. This can lead to problems with the CocoaPods installation
> [!] The `displayer [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-displayer/Pods-displayer.release.xcconfig'. This can lead to problems with the CocoaPods installation
6. I followed https://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods to solve the issue.
7. When i try to build, RNHeamp.m fails because it imports RNHeap.h which imports 'React/RCTBridgeModule.h'. The error is 'React/RCTBridgeModule.h' file not found.

**Comment by YangLeoZhao** [comment]
If it helps, 
my RCTBridgeModule.h is in node_modules/react-native/React/RCTBridgeModule.h
and my RNHeap.h is in node_modules/react-native-heap-analytics/ios/RNHeap.h

**Comment by negativetwelve** [comment]
Hi @YangLeoZhao sorry for the issue. Can you try adding these two lines to your podfile and re-run `pod install`?

https://github.com/negativetwelve/react-native-package-showcase/blob/master/ios/Podfile#L5-L6

If this works, I'll update the README. This information should be there

**Comment by YangLeoZhao** [comment]
Hey @negativetwelve Thanks for the quick response.

`pod install` gives me the following error now. 
>[!] Unable to satisfy the following requirements:
>React/BatchedBridge (from `../node_modules/react-native`)` required by `Podfile`
>None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`).
>You have either:
> * out-of-date source repos which you can update with `pod repo update` or with `pod install -->repo-update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

`pod install --repo-update` and `pod repo update` didn't help

**Comment by negativetwelve** [comment]
Ah, I forgot to ask, what version of react-native are you running?

**Comment by negativetwelve** [comment]
`React/RCTBridgeModule.h` this style of import is only available on react-native 0.40+

**Comment by YangLeoZhao** [comment]
I am using react-native: 0.44.3

>react-native -v
>react-native-cli: 2.0.1
>react-native: 0.44.3

**Comment by negativetwelve** [comment]
@YangLeoZhao did you by chance run `react-native link` on this package? Since you're using cocoapods, you should *not* have it under "Libraries" in the xcode sidebar and it should *not* be under "Linked Frameworks and Libraries" since cocoapods handles this for you

**Comment by negativetwelve** [comment]
Another thing, make sure in your xcode schema, "React" should be listed above your application and "Parallelize Build" should be unchecked. This is all under the "Build" step when clicking on your application and hitting "Edit Schema"

**Comment by YangLeoZhao** [comment]
Hey @negativetwelve, i didn't run react-native link and here is a picture of my build schema: http://imgur.com/a/HgHl4.

**Comment by YangLeoZhao** [comment]
Here is a screenshot that shows both 'BatchedBridge' and 'Core' folders exists under node_modules/react-native/Libraries. http://imgur.com/a/lVZJt

**Comment by YangLeoZhao** [comment]
If i run `pod "React", path: "../node_modules/react-native", subspecs: ["Core"]` it is ok, but if i run `pod "React", path: "../node_modules/react-native", subspecs: ["BatchedBridge", "Core"]` it complains about unable to satisfy the dependency: `React/BatchedBridge (from '../node_modules/react-native')`

**Comment by negativetwelve** [comment]
Ahh, on your version, you don't need the BatchedBridge. does it run correctly without that?

Here's the changelog where they introduced that:
https://github.com/facebook/react-native/releases/tag/v0.45.1

**Comment by negativetwelve** [comment]
Yoga is in your version so you should still need that as well

**Comment by YangLeoZhao** [comment]
Great, we are one step closer! However, i am getting Apple Mach-O Linker (Id) Error now.

Btw i also noticed in the Podfile u linked, there was no `use_frameworks!` under target, am i suppose to remove that as well?

**Comment by negativetwelve** [comment]
can you paste the error?

You can remove it, but I believe you'll need it if your project uses swift. The podfile I linked is for a demo app I use to test all the native modules I create so you can pull it and run the application on your machine if you want

**Comment by YangLeoZhao** [comment]
@negativetwelve Thanks a lot for the help. Here is the error i get when i try to build http://imgur.com/a/jRUAX

**Comment by negativetwelve** [comment]
the warnings (yellow) are actually okay, can you show the error (red)? Make sure to click on it so we can see the whole stack trace as well

**Comment by YangLeoZhao** [comment]
This is prob what you wanted. http://imgur.com/a/9JBL5

**Comment by YangLeoZhao** [comment]
Nvm i found the issue everything is working now! I just uninstalled package earlier that's why it was complaining. Thanks so much @negativetwelve really appreciate your help!

**Comment by negativetwelve** [comment]
no problem! that's great to hear! glad I could help :)

**Comment by zachgibb** [comment]
Just to lend more support to this solution, I also ran into this issue, and it was solved by adding those two lines to my `Podfile`.

https://github.com/negativetwelve/react-native-package-showcase/blob/cff5ee1808b698f6b65c5aa6697f3b85a9e614d0/ios/Podfile#L5-L6

I needed to rename `pod "Yoga"` to `pod "yoga"` first before it built correctly, however.
